site_name: Azure Developer Templates
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue grey'
markdown_extensions:
  - codehilite
nav:
    - Home: 'index.md'
    - 'Samples library':
        - 'Azure Function With Dependency Injection': 'samples/azure-function-with-dependency-injection-template.md'
        - 'Azure Application Insights SDK with ASP .NET Core': 'samples/azure-application-insights-sdk-asp-net-core-template.md'
        - 'Azure Cosmos DB SDK Repository Pattern with ASP .NET Core': 'samples/azure-cosmos-db-sdk-repository-pattern-asp-net-core-template.md'
        - 'Azure Key Vault SDK with ASP .NET Core': 'samples/azure-key-vault-sdk-asp-net-core-template.md'
        - 'Azure Notification Hub SDK with ASP .NET Core Template': 'samples/azure-notification-hub-sdk-asp-net-core-template.md'
        - 'Azure SignalR Service SDK with ASP .NET Core': 'samples/azure-signalr-service-sdk-asp-net-core-template.md'
        - 'Azure SQL DB Repository Pattern with Entity Framework Core and ASP .NET Core': 'samples/azure-sql-db-repository-pattern-asp-net-core-template.md'
        - 'Azure Service Bus SDK with ASP .NET Core': 'samples/azure-service-bus-sdk-asp-net-core-template.md'
        - 'Azure Storage Blobs SDK with ASP .NET Core': 'samples/azure-blob-storage-sdk-asp-net-core-template.md'
        - 'Azure Event Hub SDK with ASP .NET Core': 'samples/azure-event-hub-sdk-asp-net-core-template.md'
        - 'Azure Storage Queues SDK with ASP .NET Core': 'samples/azure-queue-storage-sdk-asp-net-core-template.md'
        - 'Azure Cognitive Search SDK with ASP .NET Core': 'samples/azure-cognitive-search-sdk-asp-net-core-template.md'
        - 'Azure Clients integration with ASP .NET Core DI': 'samples/azure-core-extensions-asp-net-core-template.md'
    - About the author: 'about.md'