site_name: Azure Developer Templates
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue grey'
pages:
- Home: 'index.md'
- Samples:
    - 'Azure Function With Dependency Injection Template': 'samples/sample1.md'
    - 'Azure Application Insights SDK with ASP .NET Core Template': 'samples/sample2.md'
- About the author: 'about.md'
