name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build azure-asp-net-core-starter-template
      run: dotnet build ./src/azure-asp-net-core-starter-template/AzureDeveloperTemplates.Starter.sln --configuration Release
    - name: Build azure-function-with-dependency-injection-template
      run: dotnet build ./src/azure-function-with-dependency-injection-template/AzureDeveloperTemplates.sln --configuration Release
    - name: Build azure-core-extensions-asp-net-core-template
      run: dotnet build ./src/azure-core-extensions-asp-net-core-template/AzureDeveloperTemplates.sln --configuration Release
